# Generated by Django 3.1.2 on 2020-12-06 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_auto_20201205_0648'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.TextField(default='', max_length=255)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('date_time_updated', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(default='', max_length=20)),
                ('subtotal', models.CharField(default='', max_length=4)),
                ('order_status', models.CharField(default='Assigned', max_length=12)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_who_delivered', to=settings.AUTH_USER_MODEL)),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='1', max_length=9)),
                ('user_phone', models.CharField(max_length=12)),
                ('amount', models.CharField(default='0', max_length=8)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('date_time_updated', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
