# Generated by Django 3.1.2 on 2020-12-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
