# Generated by Django 3.1.2 on 2020-12-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_address',
            field=models.TextField(default='', max_length=255),
        ),
    ]
