# Generated by Django 3.1.2 on 2020-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_address',
            field=models.TextField(default='', max_length=255, null=True),
        ),
    ]
