# Generated by Django 3.1.2 on 2020-12-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201205_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_address',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
