# Generated by Django 3.1.2 on 2020-12-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(default='1', max_length=9),
        ),
    ]
