# Generated by Django 3.1.2 on 2020-12-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_address',
        ),
    ]
