# Generated by Django 3.1.2 on 2020-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cart_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(default='', max_length=20),
        ),
    ]
