# Generated by Django 3.1.2 on 2020-12-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.IntegerField()),
                ('unit', models.CharField(default='', max_length=8, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('is_available', models.BooleanField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
