# Generated by Django 3.1.2 on 2020-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201207_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('Kg', 'Kg'), ('Gram', 'Gram')], default='', max_length=8, null=True),
        ),
    ]
