# Generated by Django 3.1.2 on 2020-12-21 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201221_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='Per 250 Grams', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
